services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo_data:/data/db
    networks:
      - meetai-network
    ports:
      - "27017:27017"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - meetai-network
    environment:
      - GROQ_API_KEY=
      - DB_URI=mongodb://host.docker.internal:27017/db
    ports:
      - "3000:3000"
    init: true
    depends_on:
      - mongo-db
    restart: unless-stopped

networks:
  meetai-network:
    driver: bridge

volumes:
  mongo_data:
